parameters:
  host: ''
  pool: ''
  ESY__CACHE_INSTALL_PATH: ''

jobs:
- job: ${{ parameters.host }}
  pool: ${{ parameters.pool }}
  steps:
  - template: ./use-esy.yml
  - task: CacheBeta@0
    inputs:
      key: |
        esy
        esy-libtools
        $(Agent.OS)
        ${{ parameters.ESY__CACHE_INSTALL_PATH }}
        $(Build.SourcesDirectory)/esy.lock/index.json
      path: ${{ parameters.ESY__CACHE_INSTALL_PATH }}
  - script: |
      rm -rf test_dir
      mkdir test_dir
    displayName: 'make test dir'
  - bash: |
      echo '{"dependencies": {"libtools" : "ulrikstrid/esy-libtools:package.json#'$(git rev-parse --short HEAD)'"}}' > package.json
    displayName: 'create test package.json'
    workingDirectory: test_dir
  - script: esy install
    displayName: 'Install esy-deps'
    workingDirectory: test_dir
  - script: esy build --verbose
    displayName: 'Build test project'
    workingDirectory: test_dir
  - script: esy x which libtoolize
    displayName: 'Test if libtools is installed'
    workingDirectory: test_dir
