parameters:
  host: ""
  pool: ""
  ESY__CACHE_INSTALL_PATH: ""

jobs:
  - job: ${{ parameters.host }}
    pool: ${{ parameters.pool }}
    steps:
      - template: ./use-esy.yml
      # - task: CacheBeta@0
      #   inputs:
      #     key: |
      #       esy
      #       esy-libtools
      #       $(Agent.OS)
      #       ${{ parameters.ESY__CACHE_INSTALL_PATH }}
      #       $(Build.SourcesDirectory)/esy.lock/index.json
      #     path: ${{ parameters.ESY__CACHE_INSTALL_PATH }}
      - bash: ./test.sh
        displayName: "Test package"
